### ISSUE TITLE
 error  'params' is assigned a value but never used  no-unused-vars

### ISSUE THREAD

**Issue by rofrol** [gabrielferreiraa/react-redux-boilerplate#4]
```
$ yarn build
yarn run v1.3.2
$ cross-env NODE_ENV=production webpack --progress --config webpack/prod.config -p
clean-webpack-plugin: /Users/romanfrolow/personal_projects/react/vendor/gabrielferreiraa/react-redux-boilerplate/docs has been removed.
 10% building modules 2/3 modules 1 active ...e_modules/babel-polyfill/lib/index.js(node:3866) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
Hash: c56b0eb35717e6d3a5d1                                                               
Version: webpack 2.2.1
Time: 19798ms
                       Asset       Size  Chunks                    Chunk Names
      media/674f50d287a8.eot     166 kB          [emitted]         
      media/912ec66d7572.svg     444 kB          [emitted]  [big]  
      media/b06871f281fe.ttf     166 kB          [emitted]         
    media/af7ae505a9ee.woff2    77.2 kB          [emitted]         
     media/fee66e712a8a.woff      98 kB          [emitted]         
main-c56b0eb35717e6d3a5d1.js    1.14 MB       0  [emitted]  [big]  main
                  index.html  571 bytes          [emitted]         
   [1] ./~/react/react.js 56 bytes {0} [built]
  [20] ./~/react-redux/es/index.js 194 bytes {0} [built]
 [102] (webpack)/buildin/global.js 509 bytes {0} [built]
 [220] ./src/main.js 462 bytes {0} [built]
 [293] ./~/react-dom/index.js 59 bytes {0} [built]
 [355] (webpack)/buildin/module.js 517 bytes {0} [built]
 [356] ./src/index.js 1.12 kB {0} [built]
 [357] ./~/babel-polyfill/lib/index.js 833 bytes {0} [built]
 [415] ./src/redux-flow/stores/configure-store.js 85 bytes {0} [built]
 [423] ./~/core-js/fn/regexp/escape.js 108 bytes {0} [built]
 [519] ./~/core-js/modules/es6.reflect.prevent-extensions.js 424 bytes {0} [built]
 [622] ./~/core-js/shim.js 8.18 kB {0} [built]
 [854] ./~/react-hot-loader/index.js 41 bytes {0} [built]
 [987] ./~/regenerator-runtime/runtime.js 24.4 kB {0} [built]
[1007] multi babel-polyfill ./src/index 40 bytes {0} [built]
    + 993 hidden modules

WARNING in ./src/containers/participants/form.js

/Users/romanfrolow/personal_projects/react/vendor/gabrielferreiraa/react-redux-boilerplate/src/containers/participants/form.js
  39:9  error  'params' is assigned a value but never used  no-unused-vars

✖ 1 problem

 @ ./src/containers/participants/index.js 21:12-29
 @ ./src/routes.js
 @ ./src/main.js
 @ ./src/index.js
 @ multi babel-polyfill ./src/index

WARNING in ./src/components/table-generator/index.js

/Users/romanfrolow/personal_projects/react/vendor/gabrielferreiraa/react-redux-boilerplate/src/components/table-generator/index.js
  12:3  error  Useless constructor  no-useless-constructor

✖ 1 problem

 @ ./src/components/content-management/index.js 15:22-59
 @ ./src/containers/participants/management.js
 @ ./src/containers/participants/index.js
 @ ./src/routes.js
 @ ./src/main.js
 @ ./src/index.js
 @ multi babel-polyfill ./src/index

ERROR in main-c56b0eb35717e6d3a5d1.js from UglifyJs
DefaultsError: `evoluate` is not a supported option
    at DefaultsError.get (eval at <anonymous> (/Users/romanfrolow/personal_projects/react/vendor/gabrielferreiraa/react-redux-boilerplate/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:86:23)
    at files.forEach (/Users/romanfrolow/personal_projects/react/vendor/gabrielferreiraa/react-redux-boilerplate/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:135:74)
    at Array.forEach (<anonymous>)
    at Compilation.compilation.plugin (/Users/romanfrolow/personal_projects/react/vendor/gabrielferreiraa/react-redux-boilerplate/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:38:11)
    at Compilation.applyPluginsAsyncSeries (/Users/romanfrolow/personal_projects/react/vendor/gabrielferreiraa/react-redux-boilerplate/node_modules/webpack/node_modules/tapable/lib/Tapable.js:206:13)
    at self.applyPluginsAsync.err (/Users/romanfrolow/personal_projects/react/vendor/gabrielferreiraa/react-redux-boilerplate/node_modules/webpack/lib/Compilation.js:626:10)
    at next (/Users/romanfrolow/personal_projects/react/vendor/gabrielferreiraa/react-redux-boilerplate/node_modules/webpack/node_modules/tapable/lib/Tapable.js:202:11)
    at Compilation.<anonymous> (/Users/romanfrolow/personal_projects/react/vendor/gabrielferreiraa/react-redux-boilerplate/node_modules/webpack/lib/ProgressPlugin.js:114:5)
    at next (/Users/romanfrolow/personal_projects/react/vendor/gabrielferreiraa/react-redux-boilerplate/node_modules/webpack/node_modules/tapable/lib/Tapable.js:204:14)
    at ExtractTextPlugin.<anonymous> (/Users/romanfrolow/personal_projects/react/vendor/gabrielferreiraa/react-redux-boilerplate/node_modules/extract-text-webpack-plugin/index.js:345:4)
    at Compilation.applyPluginsAsyncSeries (/Users/romanfrolow/personal_projects/react/vendor/gabrielferreiraa/react-redux-boilerplate/node_modules/webpack/node_modules/tapable/lib/Tapable.js:206:13)
    at sealPart2 (/Users/romanfrolow/personal_projects/react/vendor/gabrielferreiraa/react-redux-boilerplate/node_modules/webpack/lib/Compilation.js:622:9)
    at next (/Users/romanfrolow/personal_projects/react/vendor/gabrielferreiraa/react-redux-boilerplate/node_modules/webpack/node_modules/tapable/lib/Tapable.js:202:11)
    at Compilation.<anonymous> (/Users/romanfrolow/personal_projects/react/vendor/gabrielferreiraa/react-redux-boilerplate/node_modules/webpack/lib/ProgressPlugin.js:110:5)
    at next (/Users/romanfrolow/personal_projects/react/vendor/gabrielferreiraa/react-redux-boilerplate/node_modules/webpack/node_modules/tapable/lib/Tapable.js:204:14)
    at ExtractTextPlugin.<anonymous> (/Users/romanfrolow/personal_projects/react/vendor/gabrielferreiraa/react-redux-boilerplate/node_modules/extract-text-webpack-plugin/index.js:317:5)
    at /Users/romanfrolow/personal_projects/react/vendor/gabrielferreiraa/react-redux-boilerplate/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/Users/romanfrolow/personal_projects/react/vendor/gabrielferreiraa/react-redux-boilerplate/node_modules/async/dist/async.js:1050:13)
    at /Users/romanfrolow/personal_projects/react/vendor/gabrielferreiraa/react-redux-boilerplate/node_modules/async/dist/async.js:958:16
    at /Users/romanfrolow/personal_projects/react/vendor/gabrielferreiraa/react-redux-boilerplate/node_modules/extract-text-webpack-plugin/index.js:301:6
    at /Users/romanfrolow/personal_projects/react/vendor/gabrielferreiraa/react-redux-boilerplate/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/Users/romanfrolow/personal_projects/react/vendor/gabrielferreiraa/react-redux-boilerplate/node_modules/async/dist/async.js:1050:13)
    at /Users/romanfrolow/personal_projects/react/vendor/gabrielferreiraa/react-redux-boilerplate/node_modules/async/dist/async.js:958:16
    at /Users/romanfrolow/personal_projects/react/vendor/gabrielferreiraa/react-redux-boilerplate/node_modules/extract-text-webpack-plugin/index.js:298:13
    at /Users/romanfrolow/personal_projects/react/vendor/gabrielferreiraa/react-redux-boilerplate/node_modules/async/dist/async.js:3096:16
    at eachOfArrayLike (/Users/romanfrolow/personal_projects/react/vendor/gabrielferreiraa/react-redux-boilerplate/node_modules/async/dist/async.js:1055:9)
    at eachOf (/Users/romanfrolow/personal_projects/react/vendor/gabrielferreiraa/react-redux-boilerplate/node_modules/async/dist/async.js:1103:5)
    at Object.eachLimit (/Users/romanfrolow/personal_projects/react/vendor/gabrielferreiraa/react-redux-boilerplate/node_modules/async/dist/async.js:3158:5)
    at /Users/romanfrolow/personal_projects/react/vendor/gabrielferreiraa/react-redux-boilerplate/node_modules/extract-text-webpack-plugin/index.js:271:11
    at /Users/romanfrolow/personal_projects/react/vendor/gabrielferreiraa/react-redux-boilerplate/node_modules/async/dist/async.js:3096:16
Child html-webpack-plugin for "index.html":
       [0] ./~/lodash/lodash.js 540 kB {0} [built]
       [1] (webpack)/buildin/global.js 509 bytes {0} [built]
       [2] (webpack)/buildin/module.js 517 bytes {0} [built]
       [3] ./~/html-webpack-plugin/lib/loader.js!./src/template.html 921 bytes {0} [built]
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by gabrielferreiraa** [comment]
Thanks for reporting. But this is my old boilerplate, I Did make to learn work with React.

My new boilerplate is: https://github.com/gabrielferreiraa/react-boilerplate 
But it is not complete yet. I'm using CRA now.
